### ISSUE TITLE
The example is unnecessarily complicated

### ISSUE THREAD

**Issue by gazialankus** [kevmoo/qr.dart#10]
A clean function that takes in a string and renders a simple QR code would be much more useful for an average user who is just trying to render a simple QR code. The current example is intertwined with an animation and a stream.

**Comment by kevmoo** [comment]
Pull requests happily accepted :-)

**Comment by ayushin** [comment]
I guess whoever is able to understand the complex example doesn't need a simple one, and whoever needs the simple example is not able to make the PR :-D

But I second that a method to fill an arbitrary canvas with QR data would be fantastic

**Comment by gazialankus** [comment]
I had meant to share my simpler usage in AngularDart. @ayushin's comment reminded me of that. I tried to make it into a component but failed... It's been a while since I used AngularDart. Help is welcome here: https://github.com/gazialankus/qr.angulardart

**Comment by ayushin** [comment]
OK, will do my best to get it running today and submit a PR
