### ISSUE TITLE
Roll a new pub release?

### ISSUE THREAD

**Issue by lukef** [kevmoo/qr.dart#22]
Any chance of rolling a new pub release in the next week? I'm doing a bunch of updates to qr.flutter and I need the changes from #21 to make the magic happen. Not sure if you want to roll `1.2.0` or do an interim one.

**Comment by kevmoo** [comment]
Working on it! https://github.com/kevmoo/qr.dart/pull/23

**Comment by kevmoo** [comment]
published!

**Comment by lukef** [comment]
:boom: Thanks!
