### ISSUE TITLE
QrErrorCorrectionLevel

### ISSUE THREAD

**Issue by artofbeinghuman** [kevmoo/qr.dart#30]
Hi,

I just came across the QR error correction levels. If you deem it important you might want to add this info to [lib/src/error_correct_level.dart](https://github.com/kevmoo/qr.dart/blob/ca948854bbd26cc16abb4f7b626ec595ebc4905c/lib/src/error_correct_level.dart#L7)

> Level L (Low) | 7% of data bytes can be restored.
> Level M (Medium) | 15% of data bytes can be restored.
> Level Q (Quartile) | 25% of data bytes can be restored.
> Level H (High) | 30% of data bytes can be restored.
[wikipedia](https://en.wikipedia.org/wiki/QR_code#Error_correction)

So `QrErrorCorrectLevel.Q` is indeed `'Quartile'` and not `'Quality'` as it is written in https://github.com/kevmoo/qr.dart/blob/ca948854bbd26cc16abb4f7b626ec595ebc4905c/lib/src/error_correct_level.dart#L19 right now.

Cheers,
Marvin

**Comment by kevmoo** [comment]
Pull request welcome for this!

**Comment by kevmoo** [comment]
Landed the fix. Thanks!
