### ISSUE TITLE
support of modeAlphaNum

### ISSUE THREAD

**Issue by stefano2012** [kevmoo/qr.dart#33]
do you plan to implement modeAlphaNum? For standard urls it uses less space and makes the qr-codes smaller...
best,
stefano

**Comment by lukef** [comment]
It's be great to support all the QR modes. Not sure if they're fully implemented but I saw some enums that implied you can switch modes(but they all _seem_ to use the same mechanism? I'll take a look at how much work it is to do this mod (if needed).

**Comment by kevmoo** [comment]
I have no plan to implement anything beyond what's here. If I receive pull requests, I'll accept them!

**Comment by stefano2012** [comment]
Hey! Did you find out how to proceed? It should not be too difficult. It's mainly a mapping table for the specified chars...
Best, Stefano

**Comment by jtmcdole** [comment]
I'm picking this up since I just got the QrNumeric working.  Plan is:

1. Create interface QrDataSegment
2. Have QrByte & QrNumeric implement that
3. Create a new QrAlphaNumeric

Should have something soon.
