### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by vanshg395** [kevmoo/qr.dart#50]
Add More Pattern Styles as shown [here](https://www.npmjs.com/package/qr-code-styling)

**Comment by jtmcdole** [comment]
This library doesn't actual produce an image; just a row/column list of modules.  If paired with the image package; a portable qr image generator with styling demonstrated above could be made.

**Comment by kevmoo** [comment]
What @jtmcdole said!

**Comment by kevmoo** [comment]
See https://pub.dev/flutter/packages?q=dependency%3Aqr
