### ISSUE TITLE
Publish to pub.dartlang.org

### ISSUE THREAD

**Issue by adaojunior** [kevmoo/qr.dart#6]
Do you plan to publish this package to pub ?

**Comment by kevmoo** [comment]
I could. Do you want it there?

**Comment by adaojunior** [comment]
I'm not gonna use it now, but a few weeks ago I tried to find a QR code package and I could not find and I ended up creating this one [google_qr](https://pub.dartlang.org/packages/google_qr). I guess it would be nice to have this lib there as well.

**Comment by lukef** [comment]
It's now on pub! https://pub.dartlang.org/packages/qr
