### ISSUE TITLE
how to render the qrimage in flutter as a widget?

### ISSUE THREAD

**Issue by emphaticsite** [kevmoo/qr.dart#61]

**Comment by kevmoo** [comment]
See https://pub.dev/packages/barcode

**Comment by waqadArshad** [comment]
@kevmoo  can you please explain a bit because I have no idea what you meant by seeing this link. Thanks

**Comment by kevmoo** [comment]
That link is to a Flutter package that handles rendering a QR code as a widget!

**Comment by waqadArshad** [comment]
yes, after spending some time finding a way to upgrade a package that depends on this one and was rendered kinda useless after the 3.0.1 update, I ended up using the barcode package for all my needs. By the way, thank you for developing this package. qr_flutter package team is updating their package to reflect these changes and make it useful again.

**Comment by kevmoo** [comment]
Awesome!!
