### ISSUE TITLE
Reading QR from File

### ISSUE THREAD

**Issue by andreagr** [kevmoo/qr.dart#9]
Since it's possible to make a QR code, is it also possible to read one from files with this library?

**Comment by kevmoo** [comment]
You could read a String from a file and use that to create a QR code. Sure.

Nothing special in this library. There is no file format for QR as far as I
know...

**Comment by andreagr** [comment]
Thanks for the answer, my question was the opposite. I want to take a qr image from a gallery and convert it to a string...
